### ISSUE TITLE
[Network] add ability to retireve unread_bytes

### ISSUE THREAD

**Issue by azjezz** [hhvm/hsl-experimental#107]
see : https://www.php.net/manual/en/function.stream-get-meta-data.php

**Comment by fredemmott** [comment]
retitled:
- a generic thing like that will not be added
- all the other options are either n/a (e.g. all IO handles are non-blocking, no reads will timeout), or exposed in other ways (e.g. `is ReadHandle` vs `is WriteHandle`)

**Comment by fredemmott** [comment]
actually, closing, that's a PHP implementation detail, also n/a
