### ISSUE TITLE
Add `Ref<T>` class

### ISSUE THREAD

**Issue by fredemmott** [hhvm/hsl-experimental#15]
This should be included in the standard library as:
- we're expecting most users to want an object-semantics wrappers for value types. A standard library 'should' provide 'everyone needs this' functionality
- providing it in the SL will allow libraries to use it in their APIs without each library/vendor having their own thing

This class is basically a slightly fancier version of `class Ref<T> { public function __construct( public T $value ) {} }`

**Comment by Lexidor** [comment]
https://github.com/hhvm/hsl-experimental/pull/46 adds a Ref<T> to the HSL.
