### ISSUE TITLE
Random\ API consistency

### ISSUE THREAD

**Issue by fredemmott** [hhvm/hsl-experimental#17]
These are not similar to each other:

- `bool(int $rate): bool`: returns true `1/$rate` of the time
- `float(): float`: returns a float between 0.0 and 1.0
- `int(int $min = Math\INT64_MIN, int $max = Math\INT64_MAX): int`: returns an int in the specified range, which defaults to any int

My suggestion:
- make `float()` default to between FLOAT_MIN and FLOAT_MAX, and have it possible to override.
- remove `bool()`: I don't think there's a choice we can make here that is consistent. Re-add as fb\coinflip. Easily implementable as `return int(1, $rate) === 1`
- leave `int()` unchanged

**Comment by jakemco** [comment]
Floats aren't uniform between FLOAT_MIN and FLOAT_MAX though? Whereas with a "between 0.0 and 1.0" rate can be more easily uniform and then applied out to a different range via multiplication and addition.

**Comment by fredemmott** [comment]
- `float()` should definitely support supplying a range
- perhaps `float()` and `int()` shouldn't have defaults?

**Comment by jakemco** [comment]
I'd suggest: `float(float $min = 0.0, float $max = 1.0)`

**Comment by fredemmott** [comment]
float() only gets 53 bits of randomness; we can we actually do better if we natively support outside 0-1, without messing up distribution?

string(): given our other plans for Str\, I'd like to rename this to bytes()

**Comment by fredemmott** [comment]
string(): keep as-is given it takes Alphabet

**Comment by azjezz** [comment]
let's close this discussion? seems to be outdated and `HH\Lib\Random` is now part of https://github.com/hhvm/hsl , not https://github.com/hhvm/hsl-experimental
