### ISSUE TITLE
[IO] Add `MemoryHandle`

### ISSUE THREAD

**Issue by azjezz** [hhvm/hsl-experimental#58]
`MemoryHandle` is a read-write non-disposable handle that stores data in memory ( i.e. property `private string $data = '';` ), unlike `TemporaryFile` which stores data in filesystem.

`MemoryHandle` would be more efficient when dealing with a small amount of data or for mocking HTTP Requests, files ... etc. since it doesn't touch the filesystem.

**Comment by azjezz** [comment]
`MemoryHandle` probably should also  be seekable, since its possible to seek a position for read/write here - related #43

**Comment by lexidor** [comment]
Strong agree. It is something light to swap in during unit tests.

**Comment by fredemmott** [comment]
Thanks; this is reasonable, but definitely something to visit after sockets are done: until then, I want to keep the number of concrete implementations limited to the ones that will shape the overall API design, especially given the huge amount of interfaces, traits, and classes needed to implement it.

If socket support reveals shortcomings in the current API design, we'd like to keep the number of things that need updating small. This also means that we're unlikely to accept a pull request until socket support is stable.

**Comment by azjezz** [comment]
`MemoryHandle` implementation is available here : https://gist.github.com/azjezz/204575d521e68d8ed691934966fdbe35  :)
