### ISSUE TITLE
Revisit functions vs methods in IO\ and Filesystem\

### ISSUE THREAD

**Issue by fredemmott** [hhvm/hsl-experimental#8]
We chose to move from methods to functions for collections => hack arrays as using methods made it very hard to extend after the initial release - leading to `Vectors`, `Sets`, etc in FB. It feels like we'll hit a similar issue here.

**Comment by kmeht** [comment]
@fredemmott Isn't that more because the Collections classes were builtin? As long as the majority of the library is written in Hack, it should be able to be changed fairly easily.

**Comment by fredemmott** [comment]
It is straightforward to add pure hack methods to the builtin collection objects.

Methods mean that new/experimental functions either need to be used in an inconsistent way (i.e. not methods), or experimentation/development of additional methods needs to be tied to the HHVM release cycle.
