### ISSUE TITLE
[RFC | new function] Would there be interest in `Vec\read_while(Traversable, predicate)`?

### ISSUE THREAD

**Issue by lexidor** [hhvm/hsl-experimental#85]
I am using `LVec\read_while<T>(Traversable<T> $t, (function(T): bool) $predicate): vec<T>` in my own code. This operation seems basic enough to have a spot alongside `Vec\filter`.

`read_while` will act like `filter` until the predicate returns false, then it will not attempt to check the following elements.

```HACK
$ints = vec[1,2,3,2,1];
$is_less_than_three = (int $int) => $int < 3;
Vec\filter($ints, $is_less_than_three); // vec[1,2,2,1]
Vec\read_while($ints, $is_less_than_three); // vec[1,2]
```

As per the rules of the HSL, I'll need to add `Vec\read_while_with_key`, `Dict\read_while`, `Dict\read_while_with_key`, `Keyset\read_while`, and `Keyset\read_while_with_key`.

If someone can think of a name that fits in better with the rest of the hsl, I would be happy to update the proposal.

**Comment by jjergus** [comment]
I don't know, this feels maybe a little too specific for a standard library function... Maybe there's something more general that could help with the same use cases? Can you share examples of what you are using the function for in practice? That could make it more convincing :)

Maybe something like `C\first_matching[_key]($vec, $predicate)`? (basically a version of `C\any` that returns the key/value that passed the predicate or null, instead of true or false)

That could be easily combined with `Vec\slice` to get the same result, but could also be used for other things maybe.

**Comment by lexidor** [comment]
> Maybe something like C\first_matching[_key]($vec, $predicate)?

That sounds like `C\find(_key)` :stuck_out_tongue_winking_eye:
https://github.com/hhvm/hsl/blob/master/src/c/select.php#L23

> Can you share examples of what you are using the function for in practice? That could make it more convincing :)

```HACK
$lines = parse_hhconfig($path_to_hhconfig);
$important_lines = LVec\read_until($lines, $line ==> is_stop_sign($line));
$header = LVec\read_until($important_lines, $line ==> is_setting($line));
$settings = LVec\read_while(Vec\drop($important_lines, C\count($header)), $line ==> is_setting($line));
$footer = Vec\drop($important_lines, C\count($header) + C\count($settings));
```

> That could be easily combined with Vec\slice to get the same result, but could also be used for other things maybe.

It definitely could and I probably should rewrite my code like this.

```HACK
$lines = parse_hhconfig($path_to_hhconfig);
$header_start = 0;
$settings_start = C\find_key($lines, $line ==> is_setting($line));
$header = Vec\take($lines, $settings_start);
$lines = Vec\drop($lines, $settings_start);
$settings_end = C\find_key($lines, $line ==> !is_setting($line));
$settings = Vec\take($lines, $settings_end);
$lines = Vec\drop($lines, $settings_end);
$footer_end = C\find_key($lines, $line ==> is_stop_sign($line));
$footer = Vec\take($lnes, $footer_end);
```

It looks longer, because of the repeated pattern of `take, drop, ...`, but it is far more clear in what it does. The `C\count()` trick in the first example is a dirty hack.

I am going to make a `LVec\take_and_drop<T>(Traversable<T> $t, arraykey $index): (vec<T>, vec<T>)` and see if I end up using it a lot. 

That way I can write this cleaner like so:

```HACK
list($header, $lines) = LVec\take_and_drop($lines, C\find_key($lines, $line ==> is_setting($line)));
list($settings, $lines) = LVec\take_and_drop($lines, C\find_key($lines, $line ==> !is_setting($line)));
$footer = Vec\take($lines, C\find_key($lines, $line ==> is_stop_sign($line)));
```

Thanks for the idea!

**Comment by jjergus** [comment]
Do we have any other HSL functions that return tuples? That part still feels a bit weird to me, but a function that splits a vec at the given index seems pretty useful in general, I wouldn't be opposed to that...

`take_and_drop` could maybe be implemented by adding a `$limit` argument to `chunk` (like `Str\split` has) but that wouldn't work with `list(...)` :(

**Comment by lexidor** [comment]
> Do we have any other HSL functions that return tuples?

Yes we do, and exactly for the `list($a, $b) = Vec\partition($vec, $predicate)` reason.
https://github.com/hhvm/hsl/blob/master/src/vec/divide.php#L21

**Comment by jjergus** [comment]
That's a good example, thanks. Adding another function there that splits a vec at a given index seems reasonable to me, @fredemmott @kmeht what do you think?

If you don't want to read the whole discussion, the current proposal is approximately this:

```
namespace HH\Lib\Vec;
function take_and_drop(  // split? separate? divide? ...
  vec $v,
  int $idx,
): (vec, vec) {
  return tuple(take($v, $idx), drop($v, $idx));
}
```

**Comment by lexidor** [comment]
@jjergus would you mind if I made a new RFC for this one, close the current RFC and refer back to it using the hash tag syntax?

**Comment by jjergus** [comment]
I certainly don't mind :) but if the idea goes through more iterations, I'm not sure if it's useful to open a new PR after each iteration...

**Comment by jjergus** [comment]
Interestingly, I found out we have the exact equivalent of `read_while` internally (`Vec\fb\take_while`). It has existed for about 2 years and gathered about 30 callsites, which is not a lot.
