### ISSUE TITLE
[RFC | new function] `Vec\take_and_drop`

### ISSUE THREAD

**Issue by lexidor** [hhvm/hsl-experimental#86]
In the discussion about `Vec\read_while()` #85, we ended up discussing an operation that combines `Vec\take()` and `Vec\drop()`. The temporary name was `Vec\take_and_drop()`.

The idea was to have one operation for situations where `take` and `drop` are being called with the same arguments:

```HACK
$things = some_vec();
$first_50 = Vec\take($things, 50);
$rest = Vec\drop($things, 50);

list($first, $rest) = Vec\take_and_drop($things, 50);
```

This is a HSL beginner trap I have fallen for myself. This expresses your intend, but it is wasteful. The `drop` will iterate over the arguments that `take` already iterated over. The /correct/ way of doing this is with two calls to slice.

```HACK
$things = some_vec();
$first_50 = Vec\slice($things, 0, 50);
$rest = Vec\slice($things, 50);
```

Unless you have someone else tell you that this is the better way to do things or you read to implementation of the hsl, you end up writing `take`, `drop`.

**Comment by azjezz** [comment]
i don't think its a good idea to return `tuple()` here, also wouldn't `Vec\split` make more sense for the sake of consistency ? 

```hack
function split<T>(Traversable<T> $vec, int $size, ?int $limit = null): vec<vec<T>> {
  $vec = vec($vec);
  $result = vec[];
  if ($limit is nonnull && $limit === 1) {
    return vec[$vec];
  }

  invariant($limit is null || $limit > 1);
  invariant($size > 0);

  while(
    C\count($vec) > $size &&
    ($limit is null || C\count($result) < $limit))
  ) {
    $result[] = slice($vec, 0, $size);
    $vec = slice($vec, $size);
  }

  return $result;
}
```

```hack
$x = $this->getSomeVec();
$y = 10;

list($firstY, $rest) = split($x, $y, 2);
```

**Comment by jjergus** [comment]
@azjezz That already exists as `Vec\chunk()` but I don't think it works with `list($a, $b) = ...`

**Comment by fredemmott** [comment]
I'm bad at naming, but IMO something similar to array_shift (with a name that isn't shift - perhaps pop_front?) could be nice - with a signature like:

```
function pop_front<T>(inout vec<T> $foo): T
```

either throwing an exception, or returning the first element and mutating the inout element with `$foo = Vec\drop($foo, 1)`

**Comment by azjezz** [comment]
:+1:  for `array_shift` and `unshift` equivalents , have used a combination of `C\first()` and `Vec\drop` countless times ( https://github.com/nuxed/console/blob/c3bcdabc738683decb5eb0a66d423c699b2ad5e0/src/Nuxed/Console/HelpScreen.hack#L298, https://github.com/nuxed/console/blob/c3bcdabc738683decb5eb0a66d423c699b2ad5e0/src/Nuxed/Console/HelpScreen.hack#L212, https://github.com/nuxed/console/blob/605f5a50197fdde1e43214ea5cbbd9ed0545dcd6/src/Nuxed/Console/Input/Lexer.hack#L197 ....) in order to achieve this behaviour, and having a function for it would definitely help

**Comment by lexidor** [comment]
> I'm bad at naming, but IMO something similar to array_shift (with a name that isn't shift - perhaps pop_front?) could be nice - with a signature like:
> 
> ```
> function pop_front<T>(inout vec<T> $foo): T
> ```
> 
> either throwing an exception, or returning the first element and mutating the inout element with `$foo = Vec\drop($foo, 1)`

Let's also add its little brother, pop_back. 😉

**Comment by lexidor** [comment]
> I'm bad at naming, but IMO something similar to array_shift (with a name that isn't shift - perhaps pop_front?) could be nice - with a signature like:
> 
> ```
> function pop_front<T>(inout vec<T> $foo): T
> ```
> 
> either throwing an exception, or returning the first element and mutating the inout element with `$foo = Vec\drop($foo, 1)`

Let's also add its little brother, pop_back. 😉

**Comment by lexidor** [comment]
Wrong button

**Comment by jjergus** [comment]
> This is a HSL beginner trap I have fallen for myself. This expresses your intend, but it is wasteful. The drop will iterate over the arguments that take already iterated over

Perhaps we could prevent this by adding a special case to `Vec\drop` so that it uses `array_slice` instead of the `foreach` loop when dealing with a `vec`?

```
if ($traversable is vec<_>) {
  return \array_slice(...);
}
// original code
```

**Comment by fredemmott** [comment]
- `Vec\drop()` should probably take a `Container`, not a `Traversable`, avoiding the issue. The HSL has also generally been moving this way. I'm a little surprised that `Vec\drop()` is not already just a wrapper around `Vec\slice` (which does already require a container)
- `inout` parameters generally need to be invariant types -  for push_back or related functions, the type would need to be `vec<T>` anyway, not even `Container<T>`, so it can be avoided
- I no longer think that `take_and_drop()` would be a good idea:
  - we generally dislike simple compositions in the HSL
  - while the naming is clear here, I don't see clear naming for the related 'drop from end', 'insert at start' etc. I think this would end up being a one-off function, basically 'bring car+cdr to the HSL'

**Comment by jjergus** [comment]
If we can avoid the extra performance cost of

```
$first_50 = Vec\take($things, 50);
$rest = Vec\drop($things, 50);
```

compared to

```
list($first, $rest) = Vec\take_and_drop($things, 50);
```

then yeah, we probably don't need the new function.
