### ISSUE TITLE
Add lazy loaded handles / files

### ISSUE THREAD

**Issue by azjezz** [hhvm/hsl-experimental#89]
In some cases, an application would require an IO handle or a File to function, but it might not actually use it.

An example would be a request input body, the `Request` object requires `IO\SeekableReadHandle`, but there's no garunte that it will be used through out the application, therefore, opening it is a waste of resource.

currently, it is possible to implement lazy loaded `IO` handles in user land, however, its impossible to do the same for files since all interfaces are sealed.

**Comment by fredemmott** [comment]
Closing - fix is to unseal (#90)
